In [ ]:
# First, import PyTorch
#!pip install torch torchvision torchaudio
import torch

In [ ]:
def activation(x):
    """ Sigmoid activation function

        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [ ]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [ ]:
## Calculate the output of this network using the weights and bias tensors
y=activation(torch.sum(features*weights+bias))

In [ ]:
## Calculate the output of this network using matrix multiplication
# print(features.shape)
# print(weights.shape)
weights=weights.view(5,1)
y=torch.mm(weights,features)

In [ ]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [ ]:
## Your solution here
h=activation(torch.mm(features,W1)+B1)
output=activation(torch.mm(h,W2)+B2)
print(output)
#print(W1,W2)

tensor([[0.31708315]])


In [ ]:
import numpy as np
np.set_printoptions(precision=8)
a = np.random.rand(4,3)
a

array([[0.58117681, 0.86509352, 0.42174379],
       [0.77205735, 0.96940739, 0.9901001 ],
       [0.05994922, 0.82903944, 0.14677912],
       [0.6558211 , 0.03233277, 0.51281131]])

In [ ]:
torch.set_printoptions(precision=8)
b = torch.from_numpy(a)
b

tensor([[0.58117681, 0.86509352, 0.42174379],
        [0.77205735, 0.96940739, 0.99010010],
        [0.05994922, 0.82903944, 0.14677912],
        [0.65582110, 0.03233277, 0.51281131]], dtype=torch.float64)

In [ ]:
b.numpy()

array([[0.58117681, 0.86509352, 0.42174379],
       [0.77205735, 0.96940739, 0.9901001 ],
       [0.05994922, 0.82903944, 0.14677912],
       [0.6558211 , 0.03233277, 0.51281131]])

In [ ]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.16235361, 1.73018704, 0.84348758],
        [1.54411471, 1.93881477, 1.98020021],
        [0.11989843, 1.65807887, 0.29355824],
        [1.31164219, 0.06466554, 1.02562262]], dtype=torch.float64)

In [ ]:
# Numpy array matches new values from Tensor
a

array([[1.16235361, 1.73018704, 0.84348758],
       [1.54411471, 1.93881477, 1.98020021],
       [0.11989843, 1.65807887, 0.29355824],
       [1.31164219, 0.06466554, 1.02562262]])